# Generated by Django 2.0 on 2017-12-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '用户', 'verbose_name_plural': '多用户'},
        ),
    ]
