# Generated by Django 2.0 on 2017-12-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmstring',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
