# Generated by Django 2.0 on 2017-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_confirmstring_has_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmstring',
            name='has_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
