# Generated by Django 2.0 on 2017-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否已确认？'),
        ),
    ]
